// Lab 2.c
// Chris Pybus and Jeff Pistacchio
//


/*

Part 1) Write a program that responds to a external interrupt 0.
		Interrupt generated by a pushbutton to ground.
Part 2) Write 2 programs that respond to timer interrupts to 
		display elapsed time in tenths of a second.
		a. Rounds time to the tenth of a second

*/
//
//
// /INT0 is configured to be on P0.2
// UART0 is used to communicate to the user through ProCOMM or SecureCRT
//
//-------------------------------------------------------------------------------------------
// Includes
//-------------------------------------------------------------------------------------------
#include <c8051f120.h>          // SFR declarations.
#include <stdio.h>              // Necessary for printf.
#include "putget.h"             // Necessary for printf
//-------------------------------------------------------------------------------------------
// Global CONSTANTS
//-------------------------------------------------------------------------------------------
#define EXTCLK      22118400    // External oscillator frequency in Hz
#define SYSCLK      49766400    // Output of PLL derived from (EXTCLK * 9/4)
#define BAUDRATE    115200      // UART baud rate in bps
//#define BAUDRATE  19200       // UART baud rate in bps

unsigned char intrpt = 0;
unsigned int time = 0;

//-------------------------------------------------------------------------------------------
// Function PROTOTYPES
//-------------------------------------------------------------------------------------------
void main(void);
void PORT_INIT(void);
void SYSCLK_INIT(void);
void UART0_INIT(void);

void timer2_ISR (void) __interrupt 5;
//-------------------------------------------------------------------------------------------
// MAIN Routine
//-------------------------------------------------------------------------------------------
void main (void)
{
    __bit restart = 0;

    SFRPAGE = CONFIG_PAGE;

    PORT_INIT();                // Configure the Crossbar and GPIO.
    SYSCLK_INIT();              // Initialize the oscillator.
    UART0_INIT();               // Initialize UART0.

    SFRPAGE = LEGACY_PAGE;
    IT0     = 1;                // /INT0 is edge triggered, falling-edge.

    SFRPAGE = UART0_PAGE;       // Direct the output to UART0
                                // printf() must set its own SFRPAGE to UART0_PAGE
    printf("\033[2J");          // Erase screen and move cursor to the home position.
	printf("MPS Interrupt Timer\n\n\r");
	
	
    //SFRPAGE = CONFIG_PAGE;
	
    EX0     = 1;                // Enable Ext Int 0 only after everything is settled.
	printf("%x \r\n",TMR2CF);
    while (1)                   // No need to set UART0_PAGE
    {
		if (intrpt >= 6)		//if 0.1 Seconds (rounded) have passed
		{
			intrpt = 0;
			time = time + 1;
		}
		//Display Time
		//printf("%d, %d\r", time);
    	printf("Seocnds: %d.%d.\r", (time/10), (time%10));	//show time in seconds
    }
}
//-------------------------------------------------------------------------------------------
// Interrupt Service Routines
//-------------------------------------------------------------------------------------------
//

void timer2_ISR (void) __interrupt 5
{
    TF2 = 0; //clear interrupt flag
	
	intrpt = intrpt + 1; //increment interrupt global variable
	//printf("intrpt\n\n\r");
}


//-------------------------------------------------------------------------------------------
// PORT_Init
//-------------------------------------------------------------------------------------------
//
// Configure the Crossbar and GPIO ports
//
void PORT_INIT(void)
{
    char SFRPAGE_SAVE;

    SFRPAGE_SAVE = SFRPAGE;     // Save Current SFR page.

    SFRPAGE = CONFIG_PAGE;
    WDTCN   = 0xDE;             // Disable watchdog timer.
    WDTCN   = 0xAD;
    EA      = 1;                // Enable interrupts as selected.
	ET2		= 1;				// Enable timer 2 interrupt

    XBR0    = 0x04;             // Enable UART0.
    XBR1    = 0x04;             // /INT0 routed to port pin.
    XBR2    = 0x40;             // Enable Crossbar and weak pull-ups.

    P0MDOUT = 0x01;             // P0.0 (TX0) is configured as Push-Pull for output.
            // P0.1 (RX0) is configure as Open-Drain input.
            // P0.2 (SW2 through jumper wire) is configured as Open_Drain for input.
    P0      = 0x06;             // Additionally, set P0.0=0, P0.1=1, and P0.2=1.

    SFRPAGE = SFRPAGE_SAVE;     // Restore SFR page.
}

//-------------------------------------------------------------------------------------------
// SYSCLK_Init
//-------------------------------------------------------------------------------------------
//
// Initialize the system clock
//
void SYSCLK_INIT(void)
{
    int i;

    char SFRPAGE_SAVE;

    SFRPAGE_SAVE = SFRPAGE;     // Save Current SFR page.

    SFRPAGE = CONFIG_PAGE;
    OSCXCN  = 0x67;             // Start external oscillator
    for(i=0; i < 256; i++);     // Wait for the oscillator to start up.
    while(!(OSCXCN & 0x80));    // Check to see if the Crystal Oscillator Valid Flag is set.
    CLKSEL  = 0x01;             // SYSCLK derived from the External Oscillator circuit.
    OSCICN  = 0x00;             // Disable the internal oscillator.

    SFRPAGE = CONFIG_PAGE;
    PLL0CN  = 0x04;				//(4)Frequency is not locked. (2)PLL ref clock is ext osc. (0)Bias generator is deactivated
    SFRPAGE = LEGACY_PAGE;
    FLSCL   = 0x10;				//Flash Memory Control: Tells Flash that Sysclock is <= 50 MHz.
    SFRPAGE = CONFIG_PAGE;
    PLL0CN |= 0x01;				//(0) PLL bias gen is active.
    PLL0DIV = 0x04;				//Divides refclock by 8.
    PLL0FLT = 0x11;				//Clock output is 19-30 MHz. 
    PLL0MUL = 0x09;				//Multiplies re clock by 17
    for(i=0; i < 256; i++);		
    PLL0CN |= 0x02;				// PLL is enabled.
    while(!(PLL0CN & 0x10));	// Waits for PLL frequency to lock
    CLKSEL  = 0x02;             // SYSCLK derived from the PLL.

    SFRPAGE = SFRPAGE_SAVE;     // Restore SFR page.
}

//-------------------------------------------------------------------------------------------
// UART0_Init
//-------------------------------------------------------------------------------------------
//
// Configure the UART0 using Timer1, for <baudrate> and 8-N-1.
//
void UART0_INIT(void)
{
    char SFRPAGE_SAVE;

    SFRPAGE_SAVE = SFRPAGE;     // Save Current SFR page.

    SFRPAGE = TIMER01_PAGE;
    TMOD   &= ~0xF0;
    TMOD   |=  0x20;            // Timer1, Mode 2: 8-bit counter/timer with auto-reload.
    TH1     = (unsigned char)-(SYSCLK/BAUDRATE/16); // Set Timer1 reload value for baudrate
    CKCON  |= 0x10;             // Timer1 uses SYSCLK as time base.
    TL1     = TH1;
    TR1     = 1;                // Start Timer1.

	//Timer 2 config
	SFRPAGE = 0;		//Timer 2 SFR page
	
	TMR2CN &= 0xF0;  //enable timer 2
	TMR2CF &= 0xE0;	//T2 uses sysclk/12

	TMR2L = 0x00;		//Set t2 low bit
	TMR2H = 0x00;		//Set T2 High Bit
	
	TR2 = 1;			//Start Timer 2	

    SFRPAGE = UART0_PAGE;
    SCON0   = 0x50;             // Set Mode 1: 8-Bit UART
    SSTA0   = 0x10;             // UART0 baud rate divide-by-two disabled (SMOD0 = 1).
    TI0     = 1;                // Indicate TX0 ready.

    SFRPAGE = SFRPAGE_SAVE;     // Restore SFR page.
}